# Generated by Django 4.1.7 on 2023-04-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldHealthStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=10)),
                ('deaths_per_1lac_diabetes', models.DecimalField(decimal_places=5, max_digits=10)),
                ('deaths_per_1lac_alcohols', models.DecimalField(decimal_places=5, max_digits=10)),
                ('deaths_per_1lac_airpol', models.DecimalField(decimal_places=5, max_digits=10)),
                ('prob_dying_30_70_cardiovascular', models.DecimalField(decimal_places=5, max_digits=10)),
                ('deaths_per_1lac_road', models.DecimalField(decimal_places=5, max_digits=10)),
                ('percent_prevalence_tabacco', models.DecimalField(decimal_places=5, max_digits=10)),
                ('percent_obesity', models.DecimalField(decimal_places=5, max_digits=10)),
                ('percent_poor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('avail_mach_diab', models.CharField(max_length=20)),
                ('exist_protocols_diab', models.CharField(max_length=20)),
                ('adol_alcohol_percent_intake', models.DecimalField(decimal_places=5, max_digits=10)),
                ('household_Air_pol_deaths_under_5_year', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'world_health_statistics',
            },
        ),
    ]
